import { useEffect, useMemo, useState } from 'react';
import { Building2, IndianRupee, MapPin, Phone, Plus, Truck, Users } from 'lucide-react';
import toast from 'react-hot-toast';
import { api, inr, post } from '../api';
import type { Customer, Dealer } from '../types';
import { Field, Loader, Modal, PageHeader, SearchBox, Status } from '../components';

function Entities({kind}:{kind:'customer'|'dealer'}) {
  const customerMode=kind==='customer'; const endpoint=customerMode?'/customers':'/dealers';
  const [rows,setRows]=useState<(Customer|Dealer)[]>(); const [search,setSearch]=useState(''); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({name:'',phone:'',address:'',gstNumber:'',creditLimit:50000,paymentTerms:7,openingBalance:0,contactPerson:''});
  const load=()=>api<(Customer|Dealer)[]>(endpoint).then(setRows); useEffect(()=>{load();},[endpoint]);
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await post(endpoint,form);toast.success(`${customerMode?'Customer':'Dealer'} added`);setOpen(false);setForm({name:'',phone:'',address:'',gstNumber:'',creditLimit:50000,paymentTerms:7,openingBalance:0,contactPerson:''});await load();}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
  const filtered=useMemo(()=>rows?.filter(r=>`${r.name} ${r.phone} ${r.address}`.toLowerCase().includes(search.toLowerCase()))||[],[rows,search]);
  if(!rows)return <Loader/>;
  const total=rows.reduce((s,r)=>s+Number(customerMode?(r as Customer).outstanding:(r as Dealer).payable),0);
  const volume=rows.reduce((s,r)=>s+Number(customerMode?(r as Customer).totalSales:(r as Dealer).totalPurchases),0);
  return <>
    <PageHeader eyebrow={customerMode?'Accounts receivable':'Supply network'} title={customerMode?'Customers':'Dealers'} subtitle={customerMode?'Track customer business, credit limits, and every outstanding rupee.':'Manage suppliers, purchase history, and amounts you need to pay.'} action={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={17}/>Add {kind}</button>}/>
    <div className="summary-row"><div>{customerMode?<Users/>:<Truck/>}<span>Active {customerMode?'customers':'dealers'}<strong>{rows.length}</strong></span></div><div><Building2/><span>Total business<strong>{inr(volume)}</strong></span></div><div className={total?'warn':''}><IndianRupee/><span>{customerMode?'Outstanding':'Total payable'}<strong>{inr(total)}</strong></span></div></div>
    <section className="panel table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder={`Search ${customerMode?'customers':'dealers'}...`}/><select className="toolbar-select"><option>All balances</option><option>Payment due</option><option>Settled</option></select></div><div className="table-scroll"><table><thead><tr><th>{customerMode?'Customer':'Dealer'}</th><th>Contact</th><th>{customerMode?'Total sales':'Total purchases'}</th><th>{customerMode?'Received':'Paid'}</th><th>{customerMode?'Outstanding':'Payable'}</th><th>{customerMode?'Credit status':'Account status'}</th></tr></thead><tbody>{filtered.map(row=>{const c=row as Customer,d=row as Dealer; const due=Number(customerMode?c.outstanding:d.payable); const limit=Number(c.creditLimit||0); return <tr key={row.id}><td><div className="name-cell"><span className="person-avatar">{row.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span><strong>{row.name}</strong><small><MapPin size={12}/>{row.address||'No address added'}</small></span></div></td><td>{row.phone?<span className="phone"><Phone size={14}/>{row.phone}</span>:'—'}</td><td><strong>{inr(customerMode?c.totalSales:d.totalPurchases)}</strong></td><td className="positive">{inr(customerMode?c.totalReceived:d.totalPaid)}</td><td className={due?'negative':''}><strong>{inr(due)}</strong></td><td><Status tone={!due?'good':customerMode&&limit&&due>limit?'bad':'warn'}>{!due?'Settled':customerMode&&limit&&due>limit?'Over limit':'Payment due'}</Status></td></tr>})}</tbody></table></div></section>
    <Modal title={`Add ${kind}`} subtitle={customerMode?'Set contact and sensible credit terms.':'Add the supplier’s account details.'} open={open} onClose={()=>setOpen(false)}><form onSubmit={save}><div className="form-grid"><Field label={customerMode?'Customer name':'Dealer / company name'}><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field>{!customerMode&&<Field label="Contact person"><input value={form.contactPerson} onChange={e=>setForm({...form,contactPerson:e.target.value})}/></Field>}<Field label="Mobile number"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+91 98765 43210"/></Field><Field label="GST number"><input value={form.gstNumber} onChange={e=>setForm({...form,gstNumber:e.target.value})}/></Field><Field label="Address"><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></Field>{customerMode&&<><Field label="Credit limit"><div className="input-money"><span>₹</span><input type="number" min="0" value={form.creditLimit} onChange={e=>setForm({...form,creditLimit:+e.target.value})}/></div></Field><Field label="Payment terms (days)"><input type="number" min="0" value={form.paymentTerms} onChange={e=>setForm({...form,paymentTerms:+e.target.value})}/></Field></>}<Field label="Opening balance"><div className="input-money"><span>₹</span><input type="number" value={form.openingBalance} onChange={e=>setForm({...form,openingBalance:+e.target.value})}/></div></Field></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={busy}>{busy?'Saving...':`Add ${kind}`}</button></div></form></Modal>
  </>;
}

export const Customers=()=> <Entities kind="customer"/>;
export const Dealers=()=> <Entities kind="dealer"/>;
