import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Boxes, ClipboardList, Plus, SlidersHorizontal } from 'lucide-react';
import toast from 'react-hot-toast';
import { api, inr, post, shortDate } from '../api';
import type { Product, StockEntry } from '../types';
import { Empty, Field, FruitAvatar, Loader, Modal, PageHeader, SearchBox, Status } from '../components';

const initialFruit = { name: '', variety: '', unit: 'kg', purchaseRate: 0, sellingRate: 0, currentStock: 0, minStock: 0 };

export default function Inventory() {
  const [products, setProducts] = useState<Product[]>(); const [ledger, setLedger] = useState<StockEntry[]>([]);
  const [tab, setTab] = useState<'stock'|'ledger'>('stock'); const [search, setSearch] = useState('');
  const [addOpen, setAddOpen] = useState(false); const [adjustOpen, setAdjustOpen] = useState(false); const [busy, setBusy] = useState(false);
  const [fruit, setFruit] = useState(initialFruit); const [adjust, setAdjust] = useState({ productId: '', quantity: -1, reason: 'Spoiled' });
  const load = () => Promise.all([api<Product[]>('/products'), api<StockEntry[]>('/stock-ledger')]).then(([p,l]) => { setProducts(p); setLedger(l); });
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => products?.filter(p => `${p.name} ${p.variety}`.toLowerCase().includes(search.toLowerCase())) || [], [products, search]);
  async function addFruit(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { await post('/products', fruit); toast.success('Fruit added to inventory'); setAddOpen(false); setFruit(initialFruit); await load(); } catch (e) { toast.error((e as Error).message); } finally { setBusy(false); } }
  async function addAdjustment(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { await post('/stock-adjustments', adjust); toast.success('Stock adjustment recorded'); setAdjustOpen(false); await load(); } catch (e) { toast.error((e as Error).message); } finally { setBusy(false); } }
  if (!products) return <Loader/>;
  const value = products.reduce((s,p) => s + Number(p.currentStock)*Number(p.avgCost),0); const low = products.filter(p => Number(p.currentStock) <= Number(p.minStock));
  return <>
    <PageHeader eyebrow="Stock control" title="Fruit inventory" subtitle="Live quantities backed by a complete, auditable stock ledger." action={<div className="header-actions"><button className="btn secondary" onClick={() => setAdjustOpen(true)}><SlidersHorizontal size={17}/>Adjust stock</button><button className="btn primary" onClick={() => setAddOpen(true)}><Plus size={17}/>Add fruit</button></div>}/>
    <div className="summary-row"><div><Boxes/><span>Total stock value<strong>{inr(value)}</strong></span></div><div><ClipboardList/><span>Fruit varieties<strong>{products.length}</strong></span></div><div className="warn"><AlertTriangle/><span>Low stock items<strong>{low.length}</strong></span></div></div>
    <div className="tabs"><button onClick={() => setTab('stock')} className={tab==='stock'?'active':''}>Current stock</button><button onClick={() => setTab('ledger')} className={tab==='ledger'?'active':''}>Stock ledger</button></div>
    <section className="panel table-panel"><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search fruit or variety..."/><div><button className="btn compact secondary"><SlidersHorizontal size={15}/>Filter</button></div></div>
      {tab === 'stock' ? <div className="table-scroll"><table><thead><tr><th>Fruit</th><th>Current stock</th><th>Avg. cost</th><th>Selling rate</th><th>Stock value</th><th>Status</th></tr></thead><tbody>{filtered.map(p => { const pct = Math.min(100, Number(p.currentStock)/Math.max(Number(p.minStock),1)*100); const isLow=Number(p.currentStock)<=Number(p.minStock); return <tr key={p.id}><td><div className="name-cell"><FruitAvatar name={p.name}/><span><strong>{p.name}</strong><small>{p.variety || 'Standard'} · {p.unit}</small></span></div></td><td><div className="stock-cell"><strong>{Number(p.currentStock).toLocaleString('en-IN')} {p.unit}</strong><span><i className={isLow?'low':''} style={{width:`${pct}%`}}/></span></div></td><td>{inr(p.avgCost)}<small className="cell-muted">per {p.unit}</small></td><td>{inr(p.sellingRate)}<small className="cell-muted">per {p.unit}</small></td><td><strong>{inr(Number(p.currentStock)*Number(p.avgCost))}</strong></td><td><Status tone={isLow?'bad':'good'}>{isLow?'Low stock':'In stock'}</Status></td></tr>})}</tbody></table>{!filtered.length && <Empty icon={<Boxes/>} title="No fruits found" text="Try another search or add your first fruit."/>}</div>
      : <div className="table-scroll"><table><thead><tr><th>Date</th><th>Fruit</th><th>Movement</th><th>Quantity</th><th>Reference</th><th>Reason / cost</th></tr></thead><tbody>{ledger.filter(l => `${l.product.name} ${l.reference}`.toLowerCase().includes(search.toLowerCase())).map(l => <tr key={l.id}><td>{shortDate(l.date)}</td><td><div className="name-cell"><FruitAvatar name={l.product.name} size="small"/><span><strong>{l.product.name}</strong><small>{l.product.variety}</small></span></div></td><td><Status tone={l.quantity>0?'good':l.type==='SALE'?'blue':'bad'}>{l.type.replace('_',' ')}</Status></td><td className={l.quantity>0?'positive':'negative'}><strong>{l.quantity>0?'+':''}{Number(l.quantity)} {l.product.unit}</strong></td><td>{l.reference || '—'}</td><td>{l.reason || (l.unitCost ? `${inr(l.unitCost)} / ${l.product.unit}` : '—')}</td></tr>)}</tbody></table></div>}</section>
    <Modal title="Add a new fruit" subtitle="Create a stock item and optionally enter opening stock." open={addOpen} onClose={() => setAddOpen(false)}><form onSubmit={addFruit}><div className="form-grid"><Field label="Fruit name"><input required value={fruit.name} onChange={e=>setFruit({...fruit,name:e.target.value})} placeholder="e.g. Apple"/></Field><Field label="Variety"><input value={fruit.variety} onChange={e=>setFruit({...fruit,variety:e.target.value})} placeholder="e.g. Washington"/></Field><Field label="Unit"><select value={fruit.unit} onChange={e=>setFruit({...fruit,unit:e.target.value})}><option>kg</option><option>crate</option><option>box</option><option>dozen</option><option>piece</option></select></Field><Field label="Opening stock"><input type="number" min="0" step=".001" value={fruit.currentStock} onChange={e=>setFruit({...fruit,currentStock:+e.target.value})}/></Field><Field label="Purchase rate"><div className="input-money"><span>₹</span><input type="number" min="0" step=".01" value={fruit.purchaseRate} onChange={e=>setFruit({...fruit,purchaseRate:+e.target.value})}/></div></Field><Field label="Selling rate"><div className="input-money"><span>₹</span><input type="number" min="0" step=".01" value={fruit.sellingRate} onChange={e=>setFruit({...fruit,sellingRate:+e.target.value})}/></div></Field><Field label="Low-stock alert"><input type="number" min="0" step=".001" value={fruit.minStock} onChange={e=>setFruit({...fruit,minStock:+e.target.value})}/></Field></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setAddOpen(false)}>Cancel</button><button disabled={busy} className="btn primary">{busy?'Saving...':'Add fruit'}</button></div></form></Modal>
    <Modal title="Adjust stock" subtitle="Damage and corrections always create a ledger entry." open={adjustOpen} onClose={()=>setAdjustOpen(false)}><form onSubmit={addAdjustment}><div className="form-stack"><Field label="Fruit"><select required value={adjust.productId} onChange={e=>setAdjust({...adjust,productId:e.target.value})}><option value="">Choose fruit</option>{products.map(p=><option value={p.id} key={p.id}>{p.name} — {Number(p.currentStock)} {p.unit}</option>)}</select></Field><Field label="Quantity change" hint="Use a negative number for damage or wastage."><input type="number" step=".001" required value={adjust.quantity} onChange={e=>setAdjust({...adjust,quantity:+e.target.value})}/></Field><Field label="Reason"><select value={adjust.reason} onChange={e=>setAdjust({...adjust,reason:e.target.value})}><option>Spoiled</option><option>Damaged</option><option>Rotten</option><option>Weight loss</option><option>Sampling</option><option>Personal use</option><option>Correction</option></select></Field></div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setAdjustOpen(false)}>Cancel</button><button disabled={busy} className="btn primary">Record adjustment</button></div></form></Modal>
  </>;
}
